# Generated by Django 2.1.2 on 2020-04-30 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='sample_1',
        ),
        migrations.RemoveField(
            model_name='item',
            name='sample_10',
        ),
        migrations.RemoveField(
            model_name='item',
            name='sample_2',
        ),
        migrations.RemoveField(
            model_name='item',
            name='sample_3',
        ),
        migrations.RemoveField(
            model_name='item',
            name='sample_4',
        ),
        migrations.RemoveField(
            model_name='item',
            name='sample_5',
        ),
        migrations.RemoveField(
            model_name='item',
            name='sample_6',
        ),
        migrations.RemoveField(
            model_name='item',
            name='sample_8',
        ),
        migrations.RemoveField(
            model_name='item',
            name='sample_9',
        ),
        migrations.AddField(
            model_name='item',
            name='item_category',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='商品種類'),
        ),
        migrations.AddField(
            model_name='item',
            name='item_detail',
            field=models.TextField(blank=True, null=True, verbose_name='商品詳細'),
        ),
        migrations.AddField(
            model_name='item',
            name='item_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='商品ID'),
        ),
        migrations.AddField(
            model_name='item',
            name='item_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='品番'),
        ),
        migrations.AddField(
            model_name='item',
            name='item_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='単品重量(g)'),
        ),
        migrations.AlterField(
            model_name='item',
            name='sample_7',
            field=models.DateField(blank=True, null=True, verbose_name='登録日'),
        ),
    ]
