# Generated by Django 2.1.2 on 2020-04-30 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200430_1102'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='sample_7',
            new_name='item_resist_date',
        ),
        migrations.AddField(
            model_name='item',
            name='item_code',
            field=models.IntegerField(blank=True, max_length=13, null=True, verbose_name='janコード'),
        ),
        migrations.AddField(
            model_name='item',
            name='item_kind',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='商品種類'),
        ),
        migrations.AddField(
            model_name='item',
            name='item_memo',
            field=models.TextField(blank=True, null=True, verbose_name='商品詳細'),
        ),
        migrations.AddField(
            model_name='item',
            name='item_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='品番'),
        ),
        migrations.AddField(
            model_name='item',
            name='item_stock',
            field=models.IntegerField(blank=True, null=True, verbose_name='在庫数'),
        ),
        migrations.AddField(
            model_name='item',
            name='item_weight',
            field=models.IntegerField(blank=True, null=True, verbose_name='単品重量(g)'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_category',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='商品区分'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='商品名'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='商品価格(税抜)'),
        ),
    ]
