# Generated by Django 2.1.2 on 2020-05-01 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200430_1143'),
    ]

    operations = [
        migrations.CreateModel(
            name='M_Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.IntegerField(blank=True, null=True, verbose_name='商品ID')),
                ('item_category', models.CharField(blank=True, max_length=100, null=True, verbose_name='商品区分')),
                ('item_kind', models.CharField(blank=True, max_length=100, null=True, verbose_name='商品種類')),
            ],
        ),
        migrations.AlterField(
            model_name='item',
            name='item_code',
            field=models.IntegerField(blank=True, null=True, verbose_name='janコード'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_memo',
            field=models.TextField(blank=True, null=True, verbose_name='商品メモ'),
        ),
    ]
